#!/usr/bin/env ruby

# Run mailtojekyll with options
require 'optparse'
require 'highline/import'
require 'mailtojekyll'

options = {:name => nil, :age => nil}

parser = OptionParser.new do|opts|
	opts.banner = "Usage: mailtojekyll.rb [options]"
  
  opts.on('-r', '--repo repo', 'Repo') do |repo|
    options[:repo] = repo;
  end
  
	opts.on('-s', '--server server', 'Server') do |server|
		options[:server] = server;
	end

	opts.on('-u', '--user user', 'User') do |user|
		options[:user] = user;
	end
  
  opts.on('-p', '--pass pass', 'Pass') do |pass|
    options[:pass] = pass;
  end
  
  opts.on('-S', '--secret secret', 'Secret') do |secret|
    options[:secret] = secret;
  end
  
  opts.on('-I', '--imgdir imgdir', 'Imgdir') do |imgdir|
    options[:imgdir] = imgdir;
  end
  
  opts.on('-P', '--postdir postdir', 'Postdir') do |postdir|
    options[:postdir] = postdir;
  end
  
  opts.on('-l', '--layout layout', 'Layout') do |layout|
    options[:layout] = layout;
  end
  
  opts.on('-c', '--categories categories', 'Categories') do |categories|
    options[:categories] = categories;
  end

	opts.on('-h', '--help', 'Displays Help') do
		puts opts
		exit
	end
end

parser.parse!

if options[:repo] == nil
	puts 'Enter the location of your jekyll repo (e.g. /home/user/blog): '
    options[:repo] = gets.chomp
end

if options[:server] == nil
	puts 'Enter your pop account server (e.g. pop.gmail.com): '
    options[:server] = gets.chomp
end

if options[:user] == nil
	puts 'Enter your pop account username (e.g. xxxxx@gmail.com): '
    options[:user] = gets.chomp
end

if options[:pass] == nil
  options[:pass] = ask("Enter your pop account password:\n") { |q| q.echo="*" }
end

if options[:secret] == nil
	puts 'Enter your mailtojekyll secret: '
    options[:secret] = gets.chomp
end

if options[:imgdir] == nil
	puts 'Enter the location of your image directory (default: images): '
    options[:imgdir] = gets.chomp
end

if options[:postdir] == nil
	puts 'Enter the location of your image directory (default: _posts): '
    options[:postdir] = gets.chomp
end

if options[:layout] == nil
	puts 'Enter the jekyll template layout you want applied to these posts (default: post): '
    options[:layout] = gets.chomp
end

if options[:categories] == nil
	puts 'Enter the jekyll categories you want applied to these posts, separated by commas (default: latest): '
    options[:categories] = gets.chomp
end